name: Deploy Main Server to App Engine

on:
  push:
    paths:
      - "server/**"
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Firebase Account Key
      run: |
        cd server
        mkdir -p secrets
        echo "$AUTH_KEY" > secrets/serviceAccountKey.json
      env:
        AUTH_KEY: ${{ secrets.FIRESTORE_AUTH_KEY }}

    - name: Download JWT Secret Key
      run: |
        cd server/secrets
        echo "$JWT_KEY" > jwt-guid.txt
      env:
        JWT_KEY: ${{ secrets.JWT_SECRET_KEY }}

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: server/app.yaml
        version: next
        project_id: your-project
        credentials: ${{ secrets.GCP_AE_DEPLOYMENT_KEY }}